kind: pipeline
type: docker
name: json-to-db

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule init
  - git submodule update
- name: import-to-db
  image: node:lts
  volumes:
  - name: input
    path: /drone/src/src/utils/filesToImport
  environment:
    POSTGRES_USER:
      from_secret: postgres_user
    POSTGRES_PASSWORD:
      from_secret: postgres_password
  commands:
  - ls -l prisma/
  - yarn
  - yarn start

volumes:
- name: input
  host:
    path: /tmp/dir3-json
