kind: pipeline
type: docker
name: json-to-db

clone:
  disable: true

steps:
- name: clone
  image: plugins/git
  commands:
  - git clone https://github.com/doncicuto/dir3-to-db.git .
  - git submodule update
- name: import-to-db
  image: node:lts
  volumes:
  - name: input
    path: /drone/src/utils/filesToImport
  environment:
    POSTGRES_USER:
      from_secret: postgres_user
    POSTGRES_PASSWORD:
      from_secret: postgres_password
  commands:
  - yarn
  - yarn start

volumes:
- name: input
  host:
    path: /tmp/dir3-json
